name: Trigger auto deployment for py-discord-bot

on:
  push:
    branches: [ main ]
    paths:
    - '**' # This will trigger on any change in the repo, consider more specific paths if needed
    - '.github/workflows/py-discord-bot-AutoDeployTrigger-b65f0283-cb74-4d06-baea-01bdc733ca7f.yml'
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # For checkout

    steps:
      - name: Confirm Bot Workflow Version
        run: echo "RUNNING BOT WORKFLOW V2 - SHARED SP CREDS & EXPLICIT ACR"

      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PYDASHBOARDAPP_AZURE_CREDENTIALS }} # Using the dashboard's (shared) credential secret

      - name: Build and deploy container image
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./bot.Dockerfile
          registryUrl: pybotdashboardregistry.azurecr.io
          registryUsername: ${{ fromJson(secrets.PYDASHBOARDAPP_AZURE_CREDENTIALS).clientId }}
          registryPassword: ${{ fromJson(secrets.PYDASHBOARDAPP_AZURE_CREDENTIALS).clientSecret }}
          containerAppName: py-discord-bot
          resourceGroup: PythonBotAppRG
          imageToBuild: pybotdashboardregistry.azurecr.io/py-discord-bot:${{ github.sha }}
